# ??? DataSource ???????????????????????????????????????????
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
# H2 em ARQUIVO (o banco ficará salvo em ./quarkus-db.mv.db)
quarkus.datasource.jdbc.url=jdbc:h2:file:./quarkus-db
quarkus.h2.console.enabled=true
quarkus.h2.console.path=/h2-console
# ??? Hibernate ORM ????????????????????????????????????????
# drop-and-create ? recria as tabelas a cada restart (bom para desenvolvimento)
quarkus.hibernate-orm.database.generation=update
# Exibe o SQL gerado no console (útil para aprender)
quarkus.hibernate-orm.log.sql=true
# JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=http://localhost:8080
smallrye.jwt.sign.key.location=privateKey.pem
# Mostra o stack trace completo no console
quarkus.http.access-log.enabled=true
quarkus.log.level=DEBUG
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c] %s%e%n
quarkus.http.auth.proactive=false
quarkus.http.auth.permission.h2-console.paths=/h2-console,/h2-console/*
quarkus.http.auth.permission.h2-console.policy=permit
quarkus.http.auth.permission.h2-console.auth-mechanism=anonymous