# DataSource
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=

# H2 em ARQUIVO (o banco ficará salvo em ./quarkus-db.mv.db)
quarkus.datasource.jdbc.url=jdbc:h2:file:./quarkus-db

# Hibernate ORM com H2
quarkus.hibernate-orm.database.generation=update

# Exibe o SQL gerado no console (útil para aprender)
quarkus.hibernate-orm.log.sql=true

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=http://localhost:8080
smallrye.jwt.sign.key.location=privateKey.pem

# Mostra o stack trace completo no console
#quarkus.http.access-log.enabled=true
#quarkus.log.level=DEBUG
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c] %s%e%n

# H2 Console
%dev.quarkus.h2.console.enabled=true
%dev.quarkus.h2.console.path=/h2-console
%dev.quarkus.http.auth.proactive=false
%dev.quarkus.http.auth.permission.h2.paths=/h2-console,/h2-console/*
%dev.quarkus.http.auth.permission.h2.policy=permit
