# ??? DataSource ???????????????????????????????????????????
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
# H2 em ARQUIVO (o banco ficará salvo em ./quarkus-db.mv.db)
quarkus.datasource.jdbc.url=jdbc:h2:file:./quarkus-db
# ??? Hibernate ORM ????????????????????????????????????????
# drop-and-create ? recria as tabelas a cada restart (bom para desenvolvimento)
quarkus.hibernate-orm.database.generation=update
# Exibe o SQL gerado no console (útil para aprender)
quarkus.hibernate-orm.log.sql=true